version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  api:
    build: .
    depends_on:
      - db
    environment:
      - Cloudinary__CloudName=${CLOUDINARY_CLOUDNAME}
      - Cloudinary__ApiKey=${CLOUDINARY_APIKEY}
      - Cloudinary__ApiSecret=${CLOUDINARY_APISECRET}
      - ConnectionStrings__DefaultConnection=Server=db;Database=AltitudeDb;User=sa;Password=Your_password123;
    ports:
      - "5000:80"
    env_file:
      - .env